version: 2
jobs:
  build:
    docker:
      - image: rocker/verse:4.1.2
    environment:
            _R_CHECK_FORCE_SUGGESTS_: false
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: sudo apt-get update -y && sudo apt-get install libgsl-dev
      - run:
          name: Install package dependencies
          command: R -e "devtools::install_deps(dep = TRUE)"
      - run:
          name: Build package
          command: R CMD build --no-build-vignettes --ignore-vignettes .
      - run:
          name: Check package
          command: R CMD check --no-manual --no-build-vignettes --ignore-vignettes *tar.gz
      - store_test_results:
          path: tmp/tests
